=== stumoodie/VisualLanguageToolkit/src/org/pathwayeditor/businessobjects/exchange/Canvas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.pathwayeditor.org/Exchange"
    xmlns="http://www.pathwayeditor.org/Exchange" version="1.0.0" attributeFormDefault="unqualified">
    <xs:simpleType name="CanvasSerialType">
        <xs:restriction base="xs:int"/>
    </xs:simpleType>
    <xs:simpleType name="LineStyleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SOLID"/>
            <xs:enumeration value="DASHED"/>
            <xs:enumeration value="DOT"/>
            <xs:enumeration value="DASH_DOT"/>
            <xs:enumeration value="DASH_DOT_DOT"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ObjectTypeClassificationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Root"/>
            <xs:enumeration value="Shape"/>
            <xs:enumeration value="Link"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EndDecoratorTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DIAMOND"/>
            <xs:enumeration value="ARROW"/>
            <xs:enumeration value="TRIANGLE"/>
            <xs:enumeration value="EMPTY_DIAMOND"/>
            <xs:enumeration value="BAR"/>
            <xs:enumeration value="DOUBLE_BAR"/>
            <xs:enumeration value="DOUBLE_ARROW"/>
            <xs:enumeration value="EMPTY_CIRCLE"/>
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SQUARE"/>
            <xs:enumeration value="EMPTY_SQUARE"/>
            <xs:enumeration value="EMPTY_TRIANGLE"/>
            <xs:enumeration value="TRIANGLE_BAR"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType block="" name="CanvasAttributeType" abstract="true">
        <xs:attribute name="creationSerial" type="CanvasSerialType" use="required"/>
    </xs:complexType>
    <xs:simpleType name="FigureDefinitionType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="BendPointType">
        <xs:sequence>
            <xs:element name="Position" type="PointType"/>
        </xs:sequence>
        <xs:attribute name="creationSerial" type="xs:int" use="required"/>
        <xs:attribute name="indexPosn" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="PropertyType" block="">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="PropertyRefType">
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="ShapeAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType">
                <xs:sequence>
                    <xs:element name="FillColour" type="ColourType"/>
                    <xs:element name="LineColour" type="ColourType"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="PropertyRef"
                        type="PropertyRefType"/>
                    <xs:element name="FigureDefinition" type="FigureDefinitionType"/>
                </xs:sequence>
                <xs:attribute name="lineWidth" type="xs:double"/>
                <xs:attribute name="lineStyle" type="LineStyleType"> </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LinkAttributeType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="LineColour" type="ColourType"/>
                    <xs:element name="srcTerminus" type="LinkTerminusType"/>
                    <xs:element name="tgtTerminus" type="LinkTerminusType"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="PropertyRef"
                        type="PropertyRefType"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="BendPoint"
                        type="BendPointType"/>
                </xs:sequence>
                <xs:attribute name="lineStyle" type="LineStyleType" use="required"/>
                <xs:attribute name="lineWidth" type="xs:double" use="required"/>
                <xs:attribute name="objectTypeId" type="xs:int" use="required"/>
                <xs:attribute name="lastBendPointIndex" type="xs:int" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LinkTerminusType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="Location" type="PointType"/>
                    <xs:element name="DecoratorSize" type="DimensionType"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="PropertyRef"
                        type="PropertyRefType"/>
                </xs:sequence>
                <xs:attribute name="gap" type="xs:double" use="required"/>
                <xs:attribute name="endDecoratorType" type="EndDecoratorTypeType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LabelAttributeType">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType">
                <xs:sequence>
                    <xs:element name="LineColour" type="ColourType"/>
                    <xs:element name="FillColour" type="ColourType"/>
                    <xs:element name="PropertyRef" type="PropertyRefType"/>
                </xs:sequence>
                <xs:attribute name="lineStyle" type="LineStyleType" use="required"/>
                <xs:attribute name="lineWidth" type="xs:double" use="required"/>
                <xs:attribute name="noFill" type="xs:boolean" use="required"/>
                <xs:attribute name="noBorder" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="DrawingNodeAttributeType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="Location" type="PointType"/>
                    <xs:element name="Size" type="DimensionType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="RootAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TypedDrawingNodeAttributeType" abstract="true">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType">
                <xs:attribute name="objectTypeId" type="xs:int" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ColourType">
        <xs:attribute name="red" type="xs:int" use="required"/>
        <xs:attribute name="green" type="xs:int" use="required"/>
        <xs:attribute name="blue" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="PointType">
        <xs:attribute name="x" type="xs:double" use="required"/>
        <xs:attribute name="y" type="xs:double" use="required"/>
    </xs:complexType>
    <xs:complexType name="DimensionType">
        <xs:attribute name="width" type="xs:double" use="required"/>
        <xs:attribute name="height" type="xs:double" use="required"/>
    </xs:complexType>
    <xs:complexType name="ObjectTypeType">
        <xs:sequence>
            <xs:element name="description" type="DescriptionType"/>
        </xs:sequence>
        <xs:attribute name="uniqueId" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="classification" type="ObjectTypeClassificationType" use="required"/>
    </xs:complexType>
    <xs:complexType name="NotationType">
        <xs:sequence>
            <xs:element name="Description" type="DescriptionType"/>
            <xs:element maxOccurs="unbounded" name="ObjectType" type="ObjectTypeType"/>
        </xs:sequence>
        <xs:attribute name="qualifiedName" type="xs:string" use="required"/>
        <xs:attribute name="majorVersion" type="xs:int" use="required"/>
        <xs:attribute name="minorVersion" type="xs:int" use="required"/>
        <xs:attribute name="patchVersion" type="xs:int" use="required"/>
        <xs:attribute name="displayName" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="ModelType">
        <xs:sequence>
            <xs:element name="RootNode" type="RootNodeType"/>
        </xs:sequence>
        <xs:attribute name="lastNodeIndex" type="xs:int" use="required"/>
        <xs:attribute name="lastEdgeIndex" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="CompoundNodeType">
        <xs:sequence>
            <xs:element name="SubModel" type="SubModelType"/>
        </xs:sequence>
        <xs:attribute name="nodeId" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="RootNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType">
                <xs:sequence>
                    <xs:element name="rootAttribute" type="RootAttributeType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ShapeNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType">
                <xs:sequence>
                    <xs:element name="ShapeAttribute" type="ShapeAttributeType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LabelNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType">
                <xs:sequence>
                    <xs:element name="LabelAttribute" type="LabelAttributeType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="SubModelType">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="ShapeNode" type="ShapeNodeType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="LabelNode" type="LabelNodeType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="LinkEdge" type="LinkEdgeType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="RootNode" type="RootNodeType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LinkEdgeType">
        <xs:sequence>
            <xs:element name="LinkAttribute" type="LinkAttributeType"/>
        </xs:sequence>
        <xs:attribute name="linkIdx" type="xs:int" use="required"/>
        <xs:attribute name="srcNodeIdx" type="xs:int" use="required"/>
        <xs:attribute name="tgtNodeIdx" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType block="" mixed="true" name="TextAnnotationPropertyType">
        <xs:complexContent mixed="true">
            <xs:extension base="PropertyType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ListItemType">
        <xs:attribute name="idx" type="xs:int" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="ListAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="ListItem"
                        type="ListItemType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NumberAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="IntegerAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:int" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="BooleanAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="PropertyListType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="TextAnnotationProperty"
                type="TextAnnotationPropertyType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="NumberAnnotationProperty"
                type="NumberAnnotationPropertyType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="BooleanAnnotationProperty"
                type="BooleanAnnotationPropertyType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="IntegerAnnotationProperty"
                type="IntegerAnnotationPropertyType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="ListAnnotationProperty"
                type="ListAnnotationPropertyType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="canvas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Grid">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="GridSize" type="DimensionType"/>
                        </xs:sequence>
                        <xs:attribute name="snapToGrid" type="xs:boolean" use="required"/>
                        <xs:attribute name="gridOn" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Notation" type="NotationType"/>
                <xs:element name="CanvasSize" type="DimensionType"/>
                <xs:element form="unqualified" name="Background" type="ColourType"/>
                <xs:element name="Model" type="ModelType"/>
                <xs:element name="PropertyList" type="PropertyListType"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="lastCreationSerial" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="DescriptionType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== stumoodie/VisualLanguageToolkit/Acceptance Test/org/pathwayeditor/businessobjects/exchange/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<epx:canvas xmlns:epx="http://www.pathwayeditor.org/Exchange"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.pathwayeditor.org/Exchange file:/Users/smoodie/sfworkspace/BusinessObjects/schema/Canvas.xsd"
    name="Diagram name" lastCreationSerial="44">
    <Grid snapToGrid="true" gridOn="true">
        <GridSize width="10.0" height="10.0"/>
    </Grid>
    <Notation qualifiedName="org.pathwayeditor.stub.notation" majorVersion="99" minorVersion="19"
        patchVersion="9" displayName="Stub Notation">
        <Description>Stub notation description</Description>
        <ObjectType uniqueId="0" name="Root Object Type" classification="Root">
            <description>Root Object Type Description</description>
        </ObjectType>
        <ObjectType uniqueId="3" name="Shape C" classification="Shape">
            <description>Shape C Test ObjectType</description>
        </ObjectType>
        <ObjectType uniqueId="5" name="Link A" classification="Link">
            <description>Link A Object Type</description>
        </ObjectType>
        <ObjectType uniqueId="6" name="Link B" classification="Link">
            <description>Link B Object Type</description>
        </ObjectType>
        <ObjectType uniqueId="8" name="Link D" classification="Link">
            <description>Link D Object Type</description>
        </ObjectType>
        <ObjectType uniqueId="2" name="Shape B" classification="Shape">
            <description>Shape B Test ObjectType</description>
        </ObjectType>
        <ObjectType uniqueId="1" name="Shape A" classification="Shape">
            <description>Shape A Test ObjectType</description>
        </ObjectType>
        <ObjectType uniqueId="7" name="Link C" classification="Link">
            <description>Link C Object Type</description>
        </ObjectType>
        <ObjectType uniqueId="4" name="Shape D" classification="Shape">
            <description>Shape D Test ObjectType</description>
        </ObjectType>
    </Notation>
    <CanvasSize width="10.0" height="10.0"/>
    <Background red="100" green="100" blue="100"/>
    <Model lastNodeIndex="16" lastEdgeIndex="8">
        <RootNode nodeId="0">
            <SubModel>
                <ShapeNode nodeId="1">
                    <SubModel>
                        <ShapeNode nodeId="3">
                            <SubModel>
                                <LabelNode nodeId="15">
                                    <SubModel/>
                                    <LabelAttribute creationSerial="24" lineStyle="SOLID"
                                        lineWidth="1.0" noFill="true" noBorder="true">
                                        <Location x="57.0" y="57.0"/>
                                        <Size width="57.0" height="57.0"/>
                                        <LineColour red="255" green="255" blue="255"/>
                                        <FillColour red="107" green="107" blue="107"/>
                                        <PropertyRef id="2"/>
                                    </LabelAttribute>
                                </LabelNode>
                            </SubModel>
                            <ShapeAttribute creationSerial="3" objectTypeId="4" lineWidth="3.0"
                                lineStyle="DASH_DOT">
                                <Location x="53.0" y="53.0"/>
                                <Size width="53.0" height="53.0"/>
                                <FillColour red="103" green="103" blue="103"/>
                                <LineColour red="103" green="103" blue="103"/>
                                <PropertyRef id="2"/>
                                <FigureDefinition>curbounds rect</FigureDefinition>
                            </ShapeAttribute>
                        </ShapeNode>
                        <ShapeNode nodeId="4">
                            <SubModel>
                                <LabelNode nodeId="16">
                                    <SubModel/>
                                    <LabelAttribute creationSerial="25" lineStyle="SOLID"
                                        lineWidth="1.0" noFill="true" noBorder="true">
                                        <Location x="58.0" y="58.0"/>
                                        <Size width="58.0" height="58.0"/>
                                        <LineColour red="255" green="255" blue="255"/>
                                        <FillColour red="108" green="108" blue="108"/>
                                        <PropertyRef id="3"/>
                                    </LabelAttribute>
                                </LabelNode>
                            </SubModel>
                            <ShapeAttribute creationSerial="4" objectTypeId="3" lineWidth="4.0"
                                lineStyle="DASH_DOT_DOT">
                                <Location x="54.0" y="54.0"/>
                                <Size width="54.0" height="54.0"/>
                                <FillColour red="104" green="104" blue="104"/>
                                <LineColour red="104" green="104" blue="104"/>
                                <PropertyRef id="3"/>
                                <FigureDefinition>curbounds rect</FigureDefinition>
                            </ShapeAttribute>
                        </ShapeNode>
                        <LabelNode nodeId="9">
                            <SubModel/>
                            <LabelAttribute creationSerial="18" lineStyle="SOLID" lineWidth="1.0"
                                noFill="true" noBorder="true">
                                <Location x="51.0" y="51.0"/>
                                <Size width="51.0" height="51.0"/>
                                <LineColour red="255" green="255" blue="255"/>
                                <FillColour red="101" green="101" blue="101"/>
                                <PropertyRef id="1"/>
                            </LabelAttribute>
                        </LabelNode>
                        <LinkEdge linkIdx="7" srcNodeIdx="1" tgtNodeIdx="1">
                            <LinkAttribute creationSerial="16" lineStyle="DASH_DOT" lineWidth="18.0"
                                objectTypeId="5" lastBendPointIndex="0">
                                <LineColour red="108" green="108" blue="108"/>
                                <srcTerminus creationSerial="40" gap="15.0"
                                    endDecoratorType="DIAMOND">
                                    <Location x="0.0" y="0.0"/>
                                    <DecoratorSize width="25.0" height="25.0"/>
                                    <PropertyRef id="5"/>
                                </srcTerminus>
                                <tgtTerminus creationSerial="41" gap="16.0" endDecoratorType="ARROW">
                                    <Location x="0.0" y="0.0"/>
                                    <DecoratorSize width="26.0" height="26.0"/>
                                    <PropertyRef id="6"/>
                                </tgtTerminus>
                                <PropertyRef id="4"/>
                            </LinkAttribute>
                        </LinkEdge>
                        <LinkEdge linkIdx="8" srcNodeIdx="1" tgtNodeIdx="1">
                            <LinkAttribute creationSerial="17" lineStyle="DASH_DOT_DOT"
                                lineWidth="19.0" objectTypeId="5" lastBendPointIndex="0">
                                <LineColour red="109" green="109" blue="109"/>
                                <srcTerminus creationSerial="42" gap="17.0"
                                    endDecoratorType="DIAMOND">
                                    <Location x="0.0" y="0.0"/>
                                    <DecoratorSize width="27.0" height="27.0"/>
                                    <PropertyRef id="8"/>
                                </srcTerminus>
                                <tgtTerminus creationSerial="43" gap="18.0" endDecoratorType="ARROW">
                                    <Location x="0.0" y="0.0"/>
                                    <DecoratorSize width="28.0" height="28.0"/>
                                    <PropertyRef id="9"/>
                                </tgtTerminus>
                                <PropertyRef id="7"/>
                            </LinkAttribute>
                        </LinkEdge>
                    </SubModel>
                    <ShapeAttribute creationSerial="1" objectTypeId="1" lineWidth="1.0"
                        lineStyle="SOLID">
                        <Location x="51.0" y="51.0"/>
                        <Size width="51.0" height="51.0"/>
                        <FillColour red="101" green="101" blue="101"/>
                        <LineColour red="101" green="101" blue="101"/>
                        <PropertyRef id="1"/>
                        <FigureDefinition>curbounds rect</FigureDefinition>
                    </ShapeAttribute>
                </ShapeNode>
                <ShapeNode nodeId="2">
                    <SubModel>
                        <ShapeNode nodeId="5">
                            <SubModel/>
                            <ShapeAttribute creationSerial="5" objectTypeId="3" lineWidth="5.0"
                                lineStyle="DOT">
                                <Location x="55.0" y="55.0"/>
                                <Size width="55.0" height="55.0"/>
                                <FillColour red="105" green="105" blue="105"/>
                                <LineColour red="105" green="105" blue="105"/>
                                <PropertyRef id="11"/>
                                <FigureDefinition>curbounds rect</FigureDefinition>
                            </ShapeAttribute>
                        </ShapeNode>
                        <ShapeNode nodeId="6">
