=== stumoodie/VisualLanguageToolkit/schema/Canvas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.pathwayeditor.org/Exchange"
    xmlns="http://www.pathwayeditor.org/Exchange" version="1.0.0">
    <xs:simpleType name="CanvasSerialType">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>
    <xs:complexType block="" name="CanvasAttributeType" abstract="true">
        <xs:attribute name="creationSerial" type="CanvasSerialType" use="required"/>
    </xs:complexType>
    <xs:complexType name="PropertyType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="ShapeAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType">
                <xs:sequence>
                    <xs:element name="FillColour" type="ColourType"/>
                    <xs:element name="LineColour" type="ColourType"/>
                </xs:sequence>
                <xs:attribute name="lineWidth" type="xs:decimal"/>
                <xs:attribute name="lineStyle">
                    <xs:simpleType>
                        <xs:restriction base="xs:normalizedString">
                            <xs:enumeration value="SOLID,DASHED,DOT,DASHDOT,DASHDOTDOT"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LinkAttributeType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element ref="ObjectType"/>
                    <xs:element name="LineColour" type="ColourType"/>
                    <xs:element ref="Annotations"/>
                </xs:sequence>
                <xs:attribute name="srcTermSerial" type="CanvasSerialType" use="required"/>
                <xs:attribute name="tgtTermSerial" type="CanvasSerialType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LinkTerminusType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="location" type="PointType"/>
                    <xs:element ref="Annotations"/>
                </xs:sequence>
                <xs:attribute form="unqualified" name="terminusType" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:normalizedString">
                            <xs:whiteSpace value="replace"/>
                            <xs:enumeration value="S,T"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="srcTermSerial" type="CanvasSerialType" use="required"/>
                <xs:attribute name="tgtTermSerial" type="CanvasSerialType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LabelAttributeType">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="DrawingNodeAttributeType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="Location" type="PointType"/>
                    <xs:element name="Size" type="DimensionType"/>
                    <xs:element ref="Annotations"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="RootAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TypedDrawingNodeAttributeType" abstract="true">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType">
                <xs:sequence>
                    <xs:element ref="ObjectType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ColourType">
        <xs:attribute name="red" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="green" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="blue" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="PointType">
        <xs:attribute name="x" type="xs:decimal" use="required"/>
        <xs:attribute name="y" type="xs:decimal" use="required"/>
    </xs:complexType>
    <xs:complexType name="DimensionType">
        <xs:attribute name="width" type="xs:decimal" use="required"/>
        <xs:attribute name="height" type="xs:decimal" use="required"/>
    </xs:complexType>
    <xs:complexType name="ModelType">
        <xs:sequence>
            <xs:element name="RootNode" type="RootNodeType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CompoundNodeType">
        <xs:sequence>
            <xs:element ref="ChildModel"/>
        </xs:sequence>
        <xs:attribute name="nodeId" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:complexType name="RootNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ShapeNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType">
                <xs:attribute name="shapeAttributeSerial" type="CanvasSerialType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LabelNodeType">
        <xs:complexContent>
            <xs:extension base="CompoundNodeType">
                <xs:attribute name="labelAttributeSerial" type="CanvasSerialType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ChildModelType">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="ShapeNode"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="LabelNode"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="LinkEdge" type="LinkEdgeType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LinkEdgeType">
        <xs:attribute name="linkIdx" type="xs:integer" use="required"/>
        <xs:attribute name="srcNodeIdx" type="xs:integer" use="required"/>
        <xs:attribute name="tgtNodeIdx" type="xs:integer" use="required"/>
        <xs:attribute name="linkAttributeSerial" type="CanvasSerialType"/>
    </xs:complexType>
    <xs:complexType block="" mixed="true" name="TextAnnotationPropertyType">
        <xs:complexContent mixed="true">
            <xs:extension base="PropertyType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NumberAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:decimal" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="IntegerAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:integer" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="BooleanAnnotationPropertyType">
        <xs:complexContent>
            <xs:extension base="PropertyType">
                <xs:attribute name="value" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="LinkAttribute" type="LinkAttributeType"/>
    <xs:element name="RootAttribute" nillable="false" type="RootAttributeType"/>
    <xs:element name="ShapeAttribute" type="ShapeAttributeType"/>
    <xs:element name="LabelAttribute" type="LabelAttributeType"/>
    <xs:element name="LinkTerminus" type="LinkTerminusType"/>
    <xs:element name="Annotations">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="TextAnnotationProperty"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="NumberAnnotationProperty"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="BooleanAnnotationProperty"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="IntegerAnnotationProperty"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="TextAnnotationProperty" type="TextAnnotationPropertyType"/>
    <xs:element name="NumberAnnotationProperty" type="NumberAnnotationPropertyType"/>
    <xs:element name="BooleanAnnotationProperty" type="BooleanAnnotationPropertyType"/>
    <xs:element name="IntegerAnnotationProperty" type="IntegerAnnotationPropertyType"/>
    <xs:element name="Notation">
        <xs:complexType>
            <xs:attribute name="qualifiedName" type="xs:string" use="required"/>
            <xs:attribute name="majorVersion" type="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="minorVersion" type="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="patchVersion" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ObjectType">
        <xs:complexType>
            <xs:attribute name="uniqueId" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ChildModel" type="ChildModelType"/>
    <xs:element name="ShapeNode" type="ShapeNodeType"/>
    <xs:element name="LabelNode" type="LabelNodeType"/>
    <xs:element name="canvas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Grid">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="GridSize" type="DimensionType"/>
                        </xs:sequence>
                        <xs:attribute name="snapToGrid" type="xs:boolean" use="required"/>
                        <xs:attribute name="gridOn" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="Notation"/>
                <xs:element name="CanvasSize" type="DimensionType"/>
                <xs:element form="unqualified" name="Background" type="ColourType"/>
                <xs:element name="Model" type="ModelType"/>
                <xs:element ref="RootAttribute"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="ShapeAttribute"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="LabelAttribute"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="LinkAttribute"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="LinkTerminus"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== stumoodie/VisualLanguageToolkit/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<epx:canvas xmlns:epx="http://www.pathwayeditor.org/Exchange"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pathwayeditor.org/Exchange file:/Users/smoodie/sfworkspace/BusinessObjects/schema/Canvas.xsd">
    <Grid snapToGrid="true" gridOn="true">
        <GridSize width="10" height="10"/>
    </Grid>
    <epx:Notation qualifiedName="org.pathwayeditor.stub.notation"
        majorVersion="99" minorVersion="19" patchVersion="9"/>
    <CanvasSize width="10" height="10"/>
    <Background red="100" green="100" blue="100"/>
    <Model>
        <RootNode nodeId="0">
            <epx:ChildModel>
                <epx:ShapeNode nodeId="1" shapeAttributeSerial="1">
                    <epx:ChildModel>
                        <epx:ShapeNode nodeId="3" shapeAttributeSerial="3">
                            <epx:ChildModel>
                                <epx:LabelNode nodeId="15" labelAttributeSerial="24">
                                    <epx:ChildModel/>
                                </epx:LabelNode>
                            </epx:ChildModel>
                        </epx:ShapeNode>
                        <epx:ShapeNode nodeId="4" shapeAttributeSerial="4">
                            <epx:ChildModel>
                                <epx:LabelNode nodeId="16" labelAttributeSerial="25">
                                    <epx:ChildModel/>
                                </epx:LabelNode>
                            </epx:ChildModel>
                        </epx:ShapeNode>
                        <epx:LabelNode nodeId="9" labelAttributeSerial="18">
                            <epx:ChildModel/>
                        </epx:LabelNode>
                        <LinkEdge linkIdx="7" srcNodeIdx="1"
                            tgtNodeIdx="1" linkAttributeSerial="16"/>
                        <LinkEdge linkIdx="8" srcNodeIdx="1"
                            tgtNodeIdx="1" linkAttributeSerial="17"/>
                    </epx:ChildModel>
                </epx:ShapeNode>
                <epx:ShapeNode nodeId="2" shapeAttributeSerial="2">
                    <epx:ChildModel>
                        <epx:ShapeNode nodeId="5" shapeAttributeSerial="5">
                            <epx:ChildModel/>
                        </epx:ShapeNode>
                        <epx:ShapeNode nodeId="6" shapeAttributeSerial="6">
                            <epx:ChildModel>
                                <epx:ShapeNode nodeId="7" shapeAttributeSerial="7">
                                    <epx:ChildModel>
                                    <epx:ShapeNode nodeId="8" shapeAttributeSerial="8">
                                    <epx:ChildModel/>
                                    </epx:ShapeNode>
                                    </epx:ChildModel>
                                </epx:ShapeNode>
                                <LinkEdge linkIdx="4" srcNodeIdx="7"
                                    tgtNodeIdx="6" linkAttributeSerial="13"/>
                                <LinkEdge linkIdx="5" srcNodeIdx="6"
                                    tgtNodeIdx="7" linkAttributeSerial="14"/>
                            </epx:ChildModel>
                        </epx:ShapeNode>
                        <epx:LabelNode nodeId="12" labelAttributeSerial="21">
                            <epx:ChildModel/>
                        </epx:LabelNode>
                        <LinkEdge linkIdx="2" srcNodeIdx="2"
                            tgtNodeIdx="6" linkAttributeSerial="11"/>
                    </epx:ChildModel>
                </epx:ShapeNode>
                <epx:LabelNode nodeId="10" labelAttributeSerial="19">
                    <epx:ChildModel/>
                </epx:LabelNode>
                <epx:LabelNode nodeId="11" labelAttributeSerial="20">
                    <epx:ChildModel/>
                </epx:LabelNode>
                <epx:LabelNode nodeId="13" labelAttributeSerial="22">
                    <epx:ChildModel/>
                </epx:LabelNode>
                <epx:LabelNode nodeId="14" labelAttributeSerial="23">
                    <epx:ChildModel/>
                </epx:LabelNode>
                <LinkEdge linkIdx="0" srcNodeIdx="1" tgtNodeIdx="2" linkAttributeSerial="9"/>
                <LinkEdge linkIdx="1" srcNodeIdx="2" tgtNodeIdx="1" linkAttributeSerial="10"/>
                <LinkEdge linkIdx="3" srcNodeIdx="2" tgtNodeIdx="4" linkAttributeSerial="12"/>
                <LinkEdge linkIdx="6" srcNodeIdx="7" tgtNodeIdx="3" linkAttributeSerial="15"/>
            </epx:ChildModel>
        </RootNode>
    </Model>
    <epx:RootAttribute creationSerial="44">
        <Location x="0" y="0"/>
        <Size width="0" height="0"/>
        <epx:ObjectType uniqueId="0"/>
        <epx:Annotations/>
    </epx:RootAttribute>
    <epx:ShapeAttribute creationSerial="4">
        <Location x="54" y="54"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="6">
        <Location x="56" y="56"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="7">
        <Location x="57" y="57"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="2">
        <Location x="52" y="52"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="8">
        <Location x="58" y="58"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="1">
        <Location x="51" y="51"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="3">
        <Location x="53" y="53"/>
    </epx:ShapeAttribute>
    <epx:ShapeAttribute creationSerial="5">
        <Location x="55" y="55"/>
    </epx:ShapeAttribute>
    <epx:LabelAttribute creationSerial="22">
        <Location x="55" y="55"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="20">
        <Location x="53" y="53"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="24">
        <Location x="57" y="57"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="19">
        <Location x="52" y="52"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="25">
        <Location x="58" y="58"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="18">
        <Location x="51" y="51"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="21">
        <Location x="54" y="54"/>
    </epx:LabelAttribute>
    <epx:LabelAttribute creationSerial="23">
        <Location x="56" y="56"/>
    </epx:LabelAttribute>
    <epx:LinkAttribute creationSerial="9"/>
    <epx:LinkAttribute creationSerial="17"/>
    <epx:LinkAttribute creationSerial="10"/>
    <epx:LinkAttribute creationSerial="13"/>
    <epx:LinkAttribute creationSerial="16"/>
    <epx:LinkAttribute creationSerial="15"/>
    <epx:LinkAttribute creationSerial="11"/>
    <epx:LinkAttribute creationSerial="12"/>
    <epx:LinkAttribute creationSerial="14"/>
    <epx:LinkTerminus creationSerial="36"/>
    <epx:LinkTerminus creationSerial="38"/>
    <epx:LinkTerminus creationSerial="35"/>
    <epx:LinkTerminus creationSerial="27"/>
    <epx:LinkTerminus creationSerial="39"/>
    <epx:LinkTerminus creationSerial="30"/>
    <epx:LinkTerminus creationSerial="33"/>
    <epx:LinkTerminus creationSerial="41"/>
    <epx:LinkTerminus creationSerial="32"/>
    <epx:LinkTerminus creationSerial="26"/>
    <epx:LinkTerminus creationSerial="31"/>
    <epx:LinkTerminus creationSerial="42"/>
    <epx:LinkTerminus creationSerial="29"/>
    <epx:LinkTerminus creationSerial="34"/>
    <epx:LinkTerminus creationSerial="28"/>
    <epx:LinkTerminus creationSerial="43"/>
    <epx:LinkTerminus creationSerial="40"/>
    <epx:LinkTerminus creationSerial="37"/>
</epx:canvas>
