=== stumoodie/VisualLanguageToolkit/schema/Test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.pathwayeditor.org/Exchange"
    xmlns="http://www.pathwayeditor.org/Exchange">
    <xs:complexType block="" name="CanvasAttributeType">
        <xs:attribute name="creationSerial" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="ShapeAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LinkAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="LabelAttributeType">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DrawingNodeAttributeType">
        <xs:complexContent>
            <xs:extension base="CanvasAttributeType">
                <xs:sequence>
                    <xs:element name="location" type="PointType"/>
                    <xs:element name="size" type="DimensionType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="RootAttributeType">
        <xs:complexContent>
            <xs:extension base="TypedDrawingNodeAttributeType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TypedDrawingNodeAttributeType">
        <xs:complexContent>
            <xs:extension base="DrawingNodeAttributeType"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ColourType">
        <xs:attribute name="red" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="green" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="blue" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="PointType">
        <xs:attribute name="x" type="xs:decimal" use="required"/>
        <xs:attribute name="y" type="xs:decimal" use="required"/>
    </xs:complexType>
    <xs:complexType name="DimensionType">
        <xs:attribute name="width" type="xs:decimal" use="required"/>
        <xs:attribute name="height" type="xs:decimal" use="required"/>
    </xs:complexType>
    <xs:element name="Canvas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Grid">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="GridSize" type="DimensionType"/>
                        </xs:sequence>
                        <xs:attribute name="snapToGrid" type="xs:boolean" use="required"/>
                        <xs:attribute name="gridOn" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CanvasSize" type="DimensionType"/>
                <xs:element form="unqualified" name="Background" type="ColourType"/>
                <xs:sequence maxOccurs="1" minOccurs="1">
                    <xs:element maxOccurs="1" minOccurs="1" ref="RootAttribute"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="ShapeAttribute"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="LabelAttribute"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="LinkAttribute"/>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ShapeAttribute" type="ShapeAttributeType"/>
    <xs:element name="LinkAttribute" type="LinkAttributeType"/>
    <xs:element name="RootAttribute" type="RootAttributeType"/>
    <xs:element name="LabelAttribute" type="LabelAttributeType"/>
</xs:schema>

=== stumoodie/VisualLanguageToolkit/schema/TestTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<Canvas xmlns="http://www.pathwayeditor.org/Exchange"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.pathwayeditor.org/Exchange file:/Users/smoodie/sfworkspace/BusinessObjects/schema/Test.xsd">
    <Grid xmlns="" snapToGrid="true" gridOn="true">
        <GridSize width="10" height="10"/>
    </Grid>
    <CanvasSize xmlns="" width="10" height="10"/>
    <Background xmlns="" red="111" green="1" blue="10"/>
    <RootAttribute creationSerial="1">
        <location xmlns="" x="1" y="1"/>
        <size xmlns="" width="22" height="22"/>
    </RootAttribute>
    <ShapeAttribute creationSerial="33">
        <location xmlns="" x="4" y="3"/>
        <size xmlns="" width="4" height="7"/>
    </ShapeAttribute>
    
    <LabelAttribute creationSerial="11">
        <location xmlns="" x="1" y="11"/>
        <size xmlns="" width="1" height="222"/>
    </LabelAttribute>
    <LinkAttribute creationSerial="33">
        <location xmlns="" x="22" y="33"/>
        <size xmlns="" width="22" height="22"/>
    </LinkAttribute>
    
</Canvas>
